name: Build and Deploy to Azure

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend-go:latest ./server
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend-go:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend-react:latest ./client/my-app
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend-react:latest